### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by gazsy** [jhotmann/tasker-phone-modes#10]
Hello,

I do not know, why I got this error. When I tried to run the "ReadConfigFile", I got the error messages:
**"javasciptlet line: line 13 uncaught syntaxerror unexpected token } in JSON at Position 250"**
My phone is POCO F3 with MIUI 12.6 rooted (Android 11)
Simple I install profile from Taskernet, I added the all example the setting forder, and run "Setup".
After I tried to run "ReadConfigFile" and error :(

What did I wrong?

![Screenshot_2022-03-13-17-47-49-435_net dinglisch android taskerm](https://user-images.githubusercontent.com/75016804/158070325-f19bf9f6-79f1-45a3-a5f9-2a73d9c46278.jpg)
![Screenshot_2022-03-13-17-48-02-084_net dinglisch android taskerm](https://user-images.githubusercontent.com/75016804/158070328-5a71218a-ce52-44ce-9d42-d0f68954ac4e.jpg)
![Screenshot_2022-03-13-17-48-16-903_net dinglisch android taskerm](https://user-images.githubusercontent.com/75016804/158070600-bd52d5a0-6ea9-451f-a880-07a9cbad5f5f.jpg)

**Comment by jhotmann** [comment]
Can you post your config json files? The error indicates that there was an issue parsing the text into a JSON object.

**Comment by gazsy** [comment]
Hello Jordan,

I don't know what was happenned. I do the following step lot of time.
1. Install the tasker
2. Import Profile from taskernet
3. Allowed the access for tasker app
4. Run "Setup" in your profile
5. Copy all "Example" profile from and run "ReadConfig"

Today I tried again, and no error :)
I don't understand what was happened. Sorry for inconvenience.

**Comment by jhotmann** [comment]
No worries, glad you're up and running!
