### ISSUE TITLE
Error: Unexpected token 'finally'. 

### ISSUE THREAD

**Issue by benjmarshall** [jhotmann/tasker-phone-modes#2]
I am getting an error on a fresh install (import) of the tasker project. When the removeFromContext task is run i get a JavaScript error:
    Error: Unexpected token 'finally'. 

The context doesn't get removed. 

I have been through the setup task. Contexts get added ok, just can't remove them. This happens with any context i try. Can you advise how to fix?

**Comment by jhotmann** [comment]
@benjmarshall that's very weird, especially since I just double-checked and the word 'finally' doesn't even appear in the entire Modes project file.

**Comment by benjmarshall** [comment]
I've been playing a lot with this today, and figured it out. Sorry i got too deep into playing with new contexts i forgot to come back and update this till now!

It seems the xml file corrupted when i downloaded or transferred it, maybe an encoding thing, maybe something else? I did a fresh download straight to my mobile of the whole repo, then pulled in the project xml from that archive and it started working.

All sorted!
